# Generated by Django 4.1.4 on 2022-12-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Nom de l'entreprise")),
                ('address', models.CharField(max_length=120, verbose_name='addresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Numéro de téléphone')),
                ('RC', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registre de commerce')),
                ('NIF', models.CharField(blank=True, max_length=50, null=True, verbose_name='Num Ident fisc')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Créer le')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom du site')),
                ('address', models.CharField(max_length=120, verbose_name='addresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Numéro de téléphone')),
                ('RC', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registre de commerce')),
                ('NIF', models.CharField(blank=True, max_length=50, null=True, verbose_name='Num Ident fisc')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Créer le')),
                ('id_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom de la zone')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Créer le')),
                ('id_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='TagHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_nfc', models.CharField(max_length=120, verbose_name='NFC')),
                ('name', models.CharField(max_length=120, verbose_name='Nom du TAG')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordre')),
                ('observation', models.CharField(max_length=120, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Créer le')),
                ('id_Site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
                ('id_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone')),
            ],
        ),
        migrations.CreateModel(
            name='TagDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_path', models.CharField(blank=True, max_length=120, null=True, verbose_name='Lien de la memo')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('anomaly', models.TextField(blank=True, null=True, verbose_name='Anomalie')),
                ('is_checked', models.BooleanField(default=False, verbose_name='tag visité')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Créer le')),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tagheader')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Nom de l'employée")),
                ('address', models.CharField(max_length=120, verbose_name='addresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Numéro de téléphone')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Créer le')),
                ('id_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
        ),
    ]
